# Generated by Django 5.2.11 on 2026-02-13 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('max_groups', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Booth',
                'verbose_name_plural': 'Booths',
            },
        ),
        migrations.CreateModel(
            name='BoothVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='exhibition.booth')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booth Visit',
                'verbose_name_plural': 'Booth Visits',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('booth', 'leader'), name='unique_active_visit_per_booth_leader')],
            },
        ),
    ]
