# Generated by Django 5.2.11 on 2026-02-23 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoothStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.booth')),
                ('leader', models.ForeignKey(limit_choices_to={'groups__name': 'leaders'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booth Status',
                'verbose_name_plural': 'Booth Statuses',
                'unique_together': {('leader', 'booth')},
            },
        ),
    ]
