# Generated by Django 5.2.11 on 2026-02-23 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_leaderboothstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboothstatus',
            options={'verbose_name': 'وضعیت چک غرفه توسط لیدر', 'verbose_name_plural': 'وضعیت\u200cهای چک غرفه توسط لیدرها'},
        ),
        migrations.CreateModel(
            name='BoothGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_count', models.PositiveIntegerField(verbose_name='تعداد افراد گروه')),
                ('group_type', models.CharField(choices=[('girl', 'دختر'), ('boy', 'پسر'), ('mixed', 'ترکیبی'), ('family', 'خانواده'), ('special', 'ویژه')], max_length=20, verbose_name='نوع گروه')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='exhibition.booth')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گروه بازدیدکننده',
                'verbose_name_plural': 'گروه\u200cهای بازدیدکننده',
                'ordering': ['-registered_at'],
            },
        ),
    ]
