# Generated by Django 5.2.11 on 2026-02-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_alter_leaderboothstatus_options_boothgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boothgroup',
            options={'verbose_name': 'گروه لیدر', 'verbose_name_plural': 'گروه\u200cهای لیدرها'},
        ),
        migrations.RemoveField(
            model_name='boothgroup',
            name='booth',
        ),
        migrations.AddField(
            model_name='booth',
            name='current_visitors',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدیدکنندگان فعلی'),
        ),
        migrations.AlterField(
            model_name='boothgroup',
            name='registered_by',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'leaders'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
