# Generated by Django 5.2.11 on 2026-02-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_alter_boothgroup_options_remove_boothgroup_booth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoothGroup',
        ),
    ]
